# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "498a680bfcbe3aa4ea0293bb5a0f7742"
application_url = "https://tokyo-parents-include-logan.trycloudflare.com"
embedded = true
name = "presia"
handle = "presia"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tokyo-parents-include-logan.trycloudflare.com/auth/callback",
  "https://tokyo-parents-include-logan.trycloudflare.com/auth/shopify/callback",
  "https://tokyo-parents-include-logan.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "presiaonline.myshopify.com"
automatically_update_urls_on_dev = true
